import '@/styles/globals.css';

import { AntdRegistry } from '@ant-design/nextjs-registry';
import type { Metadata } from 'next';
import { Inter, Nunito_Sans } from 'next/font/google';

import StyleReactProvider from '@/styles/StyleReactProvider';

import ReactQueryClientProvider from '../components/config/ReactQueryClientProvider';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});
const nunitoSans = Nunito_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-nunito-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${nunitoSans.variable}`}>
      <body>
        <ReactQueryClientProvider>
          <StyleReactProvider>
            <AntdRegistry>{children}</AntdRegistry>
          </StyleReactProvider>
        </ReactQueryClientProvider>
      </body>
    </html>
  );
}
